spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: jdbc:mysql://localhost:3306/oomall?serverTimezone=GMT%2B8&useUnicode=true&characterEncoding=utf-8
#    username: root
#    password: Kaixindian
    url: jdbc:mysql://47.52.88.176:3306/DB3_3
    username: user3_3
    password: ooad3
#    type: com.alibaba.druid.pool.DruidDataSource
  #    druid:
  #      filter:
  #        stat:
  #          log-slow-sql:true
  #          slow-sql-millis:100
  application:
    name: shareService

mybatis:
  type-aliases-package: xmu.oomall.domain
  mapper-locations: classpath:xmu.oomall.mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true

logging:
  level:
    org.springframework.web: info
    root: error


#eureka:
#  client:
#    service-url:
#      defaultZone: http://ooad33.top:8081/eureka
#  instance:
#    prefer-ip-address: true
#    #    ip-address: 127.0.0.1
#    lease-expiration-duration-in-seconds: 90
#    lease-renewal-interval-in-seconds: 30

#oomall:
#  host: 192.168.1.141
#  port: 3400
#  user: 10086
#  password: 10086
#  adminuser: 10086
#  adminpassword: 10086
