spring:
  profiles:
    active: local
#  application:
#    name: shareService
#  datasource:
#    driver-class-name: com.mysql.cj.jdbc.Driver
#    url: dbc:mysql://101.132.152.28:3306/oomall
#    username: oomall
#    password: OOAD3-4wmtnl
#    type: com.alibaba.druid.pool.DruidDataSource
#    druid:
#      #初始化时建立物理连接的个数
#      initial-size: 1
#      #最小连接池数量
#      min-idle: 1
#      #最大连接池数量
#      max-active: 3
#      #获取连接时最大等待时间
#      max-wait: 60000
#      #配置监控页面访问登录名及密码
#      stat-view-servlet:
#        enabled: true
#      # 访问路径为/druid时，跳转到StatViewServlet
#        url-pattern: /druid/*
#      # 是否能够重置数据
#        reset-enable: false
#      # 需要账号密码才能访问控制台
#        login-username: admin
#        login-password: 123456
#      filter:
#        stat:
#          #是否开启慢sql查询监控
#          log-slow-sql: true
#          #慢SQL执行时间
#          slow-sql-millis: 100
#      validation-query: select 1
#    tomcat:
#      max-active: 5
#
#
#mybatis:
#  type-aliases-package: xmu.oomall.domain
#  mapper-locations: classpath:xmu.oomall.mapper/*.xml
#  configuration:
#    map-underscore-to-camel-case: true

logging:
  level:
    org.springframework.web: info
#    org.springframework.boot.autoconfigure: ERROR
    root: error

    xmu:
      oomall:
        controller: debug
        service: debug
        dao: debug
        mapper: debug
        domain: debug

eureka:
  client:
    service-url:
      defaultZone: http://47.100.91.153:3500/eureka/
  instance:
    prefer-ip-address: true
    ip-address: 106.15.249.35
    non-secure-port: 3333
#    lease-expiration-duration-in-seco/nds: 90
#    lease-renewal-interval-in-seconds: 30
#    instance-id: ${spring.cloud.client.ip-address}:${server.port}
server:
  port: 3333

feign:
  hystrix:
    enabled: true
  client:
    config:
      share:
        connectTimeout: 120000
        readTimeout: 120000
  compression:
    request:
      enabled: true
      mime-types: text/html,application/xml,application/json
      min-request-size: 2048
    response:
      enabled: true

oomall:
  host: 192.168.1.145
  port: 3400
  user: 10086
  password: 10086
  adminuser: 10086
  adminpassword: 10086
