server:
  port: 8080

spring:
  application:
    name: orderService
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver

    url: jdbc:mysql://127.0.0.1:3306/litmall
    username: root
    password: 123456

mybatis:
  type-aliases-package: domain
  mapper-locations: classpath:mapper/OrderMapper.xml
  configuration:
    map-underscore-to-camel-case: true
logging:
  level:
    litmall.orderservice.controller: debug
    litmall.orderservice.service: debug
    litmall.orderservice.dao: debug
    litmall.orderservice.mapper: debug
    litmall.orderservice.domain: debug



